name: Publish release

on:
  workflow_call:
    inputs:
      slack-channel:
        required: false
        type: string
        default: 'metamask-snaps'
      slack-icon-url:
        required: false
        type: string
        default: 'https://raw.githubusercontent.com/MetaMask/action-npm-publish/main/robo.png'
      slack-subteam:
        required: false
        type: string
      slack-username:
        required: false
        type: string
        default: 'MetaMask bot'
    secrets:
      SLACK_WEBHOOK_URL:
        required: false
      PUBLISH_PAGES_TOKEN:
        required: true
      SEGMENT_PRODUCTION_WRITE_KEY:
        required: true
      GATSBY_INDEXER_API_BASE_URL:
        required: true
      GATSBY_INDEXER_API_KEY:
        required: true

jobs:
  publish-release:
    name: Publish release
    environment: publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: MetaMask/action-publish-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-release-to-gh-pages:
    name: Publish site to `gh-pages`
    needs:
      - publish-release
    permissions:
      contents: write
    uses: ./.github/workflows/publish-site.yml
    with:
      destination_dir: .
    secrets:
      PUBLISH_PAGES_TOKEN: ${{ secrets.PUBLISH_PAGES_TOKEN }}
      SEGMENT_PRODUCTION_WRITE_KEY: ${{ secrets.SEGMENT_PRODUCTION_WRITE_KEY }}
      GATSBY_INDEXER_API_BASE_URL: ${{ secrets.GATSBY_INDEXER_API_BASE_URL }}
      GATSBY_INDEXER_API_KEY: ${{ secrets.GATSBY_INDEXER_API_KEY }}
