name: Publish Manually
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true

jobs:
  publish-release-to-gh-pages:
    name: Publish site to `gh-pages`
    permissions:
      contents: write
    uses: ./.github/workflows/publish-site.yml
    with:
      destination_dir: .
    secrets:
      PUBLISH_PAGES_TOKEN: ${{ secrets.PUBLISH_PAGES_TOKEN }}
      SEGMENT_PRODUCTION_WRITE_KEY: ${{ secrets.SEGMENT_PRODUCTION_WRITE_KEY }}
